import { Proposal, Space } from "@/lib/types";

const mockAuthors = {
  arbitrum: "0x8F3f6c68A2d95E6a8aB6A3384D4B1dA7D4cDb423",
  aave: "0x3D1f2A46B9D8C5F7a6E4B2C9A0d1E3F8B7C6D5A4",
  ens: "0x6C7F8A9B0d1E2F3A4B5C6D7E8F9A0b1C2D3E4F5A",
  uniswap: "0x9A4f6D8B2C1E3F5a7B9D0c2E4F6A8b1C3D5E7F9A",
} as const;

function getSnapshotProfileUrl(address: string) {
  return `https://snapshot.org/#/profile/${encodeURIComponent(address)}`;
}

export const spaces: Space[] = [
  {
    slug: "arbitrum-dao",
    name: "Arbitrum DAO",
    tagline: "Treasury, incentive programs, and chain-level policy.",
    verified: true,
    flagged: false,
    hibernated: false,
    turbo: false,
    followers: 118400,
    proposals: 482,
    activeProposals: 3,
    votes: 1823400,
    categories: ["Layer 2", "Treasury", "Grants"],
    activityScore: 95,
    website: "https://arbitrum.foundation",
    forum: "https://forum.arbitrum.foundation",
    twitter: "arbitrum",
    github: "OffchainLabs",
    coingecko: "arbitrum",
    summary: "Arbitrum DAO governs one of the largest L2 ecosystems, with treasury allocation and growth programs frequently shaping market structure.",
    avatar: null,
  },
  {
    slug: "aave-governance",
    name: "Aave Governance",
    tagline: "Risk parameter changes and protocol upgrades.",
    verified: true,
    flagged: false,
    hibernated: false,
    turbo: false,
    followers: 96400,
    proposals: 356,
    activeProposals: 2,
    votes: 1412500,
    categories: ["Lending", "Risk", "Protocol"],
    activityScore: 92,
    website: "https://aave.com",
    forum: "https://governance.aave.com",
    twitter: "aave",
    github: "aave",
    coingecko: "aave",
    summary: "Aave governance is high-signal for collateral policy, emissions, listings, and technical upgrades across deployments.",
    avatar: null,
  },
  {
    slug: "ens-dao",
    name: "ENS DAO",
    tagline: "Stewardship of identity infrastructure on Ethereum.",
    verified: true,
    flagged: false,
    hibernated: false,
    turbo: false,
    followers: 55100,
    proposals: 188,
    activeProposals: 1,
    votes: 624000,
    categories: ["Identity", "Public Goods"],
    activityScore: 76,
    website: "https://ens.domains",
    forum: "https://discuss.ens.domains",
    twitter: "ensdomains",
    github: "ensdomains",
    coingecko: "ethereum-name-service",
    summary: "ENS DAO proposals often blend protocol maintenance with ecosystem funding and long-range governance process design.",
    avatar: null,
  },
  {
    slug: "uniswap-governance",
    name: "Uniswap Governance",
    tagline: "Delegation, fee switches, deployments, and incentives.",
    verified: true,
    flagged: false,
    hibernated: false,
    turbo: false,
    followers: 143200,
    proposals: 401,
    activeProposals: 2,
    votes: 2156700,
    categories: ["DEX", "Treasury", "Deployment"],
    activityScore: 89,
    website: "https://uniswap.org",
    forum: "https://gov.uniswap.org",
    twitter: "Uniswap",
    github: "Uniswap",
    coingecko: "uniswap",
    summary: "Uniswap governance is where liquidity incentives, treasury deployment, and strategic expansion decisions converge.",
    avatar: null,
  }
];

export const proposals: Proposal[] = [
  {
    id: "arb-stip-bridge-audit",
    title: "Expand STIP Bridge Budget for Cross-Chain Security Audits",
    protocol: "Arbitrum DAO",
    spaceSlug: "arbitrum-dao",
    spaceAvatar: null,
    author: mockAuthors.arbitrum,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.arbitrum),
    status: "Active",
    publishedAt: "2026-04-18T08:00:00Z",
    closesAt: "2026-04-24T08:00:00Z",
    heat: 94,
    votesCount: 312,
    type: "single-choice",
    labels: ["treasury", "security"],
    quorum: 100000000,
    quorumType: "balance",
    app: "snapshot",
    discussion: "https://forum.arbitrum.foundation/t/stip-bridge-audit/123",
    flagged: false,
    summary: "Seeks additional budget allocation to fund independent audits for bridge-related incentive flows and emergency controls.",
    body: null,
    discussionUrl: "https://forum.arbitrum.foundation/t/stip-bridge-audit/123",
    proposalUrl: "https://snapshot.box"
  },
  {
    id: "aave-emode-refresh",
    title: "Refresh E-Mode Parameters for LST Collateral Markets",
    protocol: "Aave Governance",
    spaceSlug: "aave-governance",
    spaceAvatar: null,
    author: mockAuthors.aave,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.aave),
    status: "Upcoming",
    publishedAt: "2026-04-19T12:00:00Z",
    closesAt: "2026-04-27T12:00:00Z",
    heat: 88,
    votesCount: 198,
    type: "basic",
    labels: ["risk", "parameters"],
    quorum: 320000,
    quorumType: "balance",
    app: "snapshot",
    discussion: "https://governance.aave.com/t/emode-refresh/456",
    flagged: false,
    summary: "Revises liquidation thresholds and borrow caps for liquid staking token corridors to reflect current volatility and liquidity depth.",
    body: null,
    discussionUrl: "https://governance.aave.com/t/emode-refresh/456",
    proposalUrl: "https://snapshot.box"
  },
  {
    id: "ens-metagov-charter",
    title: "Ratify Meta-Governance Charter for Public Goods Allocations",
    protocol: "ENS DAO",
    spaceSlug: "ens-dao",
    spaceAvatar: null,
    author: mockAuthors.ens,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.ens),
    status: "Closed",
    publishedAt: "2026-04-10T09:00:00Z",
    closesAt: "2026-04-16T09:00:00Z",
    heat: 71,
    votesCount: 84,
    type: "single-choice",
    labels: ["governance", "public-goods"],
    quorum: null,
    quorumType: null,
    app: "snapshot",
    discussion: "https://discuss.ens.domains/t/metagov-charter/789",
    flagged: false,
    summary: "Defines principles and review cadence for how ENS delegates participate in cross-protocol public goods coordination.",
    body: null,
    discussionUrl: "https://discuss.ens.domains/t/metagov-charter/789",
    proposalUrl: "https://snapshot.box"
  },
  {
    id: "uni-deployment-northstar",
    title: "Northstar Deployment Framework for New Rollup Markets",
    protocol: "Uniswap Governance",
    spaceSlug: "uniswap-governance",
    spaceAvatar: null,
    author: mockAuthors.uniswap,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.uniswap),
    status: "Executed",
    publishedAt: "2026-04-03T15:00:00Z",
    closesAt: "2026-04-11T15:00:00Z",
    heat: 83,
    votesCount: 441,
    type: "weighted",
    labels: ["deployment", "framework"],
    quorum: 40000000,
    quorumType: "balance",
    app: "snapshot",
    discussion: "https://gov.uniswap.org/t/northstar-framework/321",
    flagged: false,
    summary: "Approves a framework for evaluating and sequencing Uniswap deployments across emerging rollup ecosystems.",
    body: null,
    discussionUrl: "https://gov.uniswap.org/t/northstar-framework/321",
    proposalUrl: "https://snapshot.box"
  },
  {
    id: "arb-delegate-attestation",
    title: "Delegate Attestation Registry for Conflict Disclosure",
    protocol: "Arbitrum DAO",
    spaceSlug: "arbitrum-dao",
    spaceAvatar: null,
    author: mockAuthors.arbitrum,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.arbitrum),
    status: "Active",
    publishedAt: "2026-04-17T08:00:00Z",
    closesAt: "2026-04-22T08:00:00Z",
    heat: 79,
    votesCount: 167,
    type: "single-choice",
    labels: ["governance"],
    quorum: null,
    quorumType: null,
    app: "snapshot",
    discussion: "https://forum.arbitrum.foundation/t/delegate-attestation/654",
    flagged: false,
    summary: "Creates a structured public registry for delegate affiliations and compensation disclosures.",
    body: null,
    discussionUrl: "https://forum.arbitrum.foundation/t/delegate-attestation/654",
    proposalUrl: "https://snapshot.box"
  },
  {
    id: "aave-safety-module-review",
    title: "Commission Independent Review of Safety Module Migration",
    protocol: "Aave Governance",
    spaceSlug: "aave-governance",
    spaceAvatar: null,
    author: mockAuthors.aave,
    authorProfileUrl: getSnapshotProfileUrl(mockAuthors.aave),
    status: "Active",
    publishedAt: "2026-04-20T06:00:00Z",
    closesAt: "2026-04-28T06:00:00Z",
    heat: 97,
    votesCount: 523,
    type: "basic",
    labels: ["risk", "safety-module"],
    quorum: 320000,
    quorumType: "balance",
    app: "snapshot",
    discussion: "https://governance.aave.com/t/safety-module-review/987",
    flagged: false,
    summary: "Requests an external review of the planned Safety Module migration, focusing on slashing assumptions and liquidity coordination.",
    body: null,
    discussionUrl: "https://governance.aave.com/t/safety-module-review/987",
    proposalUrl: "https://snapshot.box"
  }
];

export function getProposal(id: string) {
  return proposals.find((proposal) => proposal.id === id);
}

export function getSpace(slug: string) {
  return spaces.find((space) => space.slug === slug);
}

export function getSpaceProposals(slug: string) {
  return proposals.filter((proposal) => proposal.spaceSlug === slug);
}
